export enum VERIFY_SOLUTIONS {
  EMPTY_INPUT = "EMPTY_INPUT",
  INVALID_CHAR = "INVALD_CHAR",
  INVALID_PARENTHESIS = "INVALID_PARENTHESIS",
  INVALD_NUMBERS = "INVALID_NUMBERS",
  INVALD_INPUT = "INVALID_INPUT",
  INVALD_ANSWER = "INVALID_ANSWER",
  CORRECT_ANSWER = "CORRECT_ANSWER",
}
